### ISSUE TITLE
Correggere Github Action per SQL Server 2017

### ISSUE THREAD

**Issue by FrancescoTekapp** [Tekapp-SRL/Cent-LAB#3]
Questa nuova Action va in errore

https://github.com/Tekapp-SRL/Cent-LAB/actions/runs/471710923

Questa la riga in errore: https://github.com/Tekapp-SRL/Cent-LAB/blob/09cc9f8055e6242143859dedf7da8f1b4829c5bf/bin/sqlserver/sqlserver2017.Dockerfile#L12

**Comment by FrancescoTekapp** [comment]
![image](https://user-images.githubusercontent.com/38101130/104016819-544b0600-51b7-11eb-9eaf-9116988cba57.png)

**Comment by MatteoTekapp** [comment]
ho risolto la problematica aggiungendo mkdir -p inoltre per SQL 2017 ho scaricato Adventureworks 2017 in quanto il 2019 non era compatibile con sql Server 2017 adesso anche la versione 2017 è funzionante
